import "dotenv/config";

const ENV = process.env;

export const API = {
    KEY: ENV.API_KEY,
    IDENTIFIER: ENV.API_IDENTIFIER,
    PASSWORD: ENV.API_PASSWORD,
    BASE_URL: `${ENV.BASE_URL}${ENV.API_PATH}`,
    WS_URL: ENV.WS_BASE_URL,
};

export const RISK = {
    PER_TRADE: 0.03,
    MAX_HOLD_TIME: 24 * 60,
    DAILY_FORCED_CLOSE_UTC: true,
    DAILY_LAST_ENTRY_MINUTE_UTC: 22 * 60,
    DAILY_CLOSE_MINUTE_UTC: 22 * 60,
    FRIDAY_LAST_ENTRY_HOUR_UTC: 18,
    FRIDAY_CLOSE_HOUR_UTC: 20,
    REQUIRED_SCORE: 3,
    WEEKEND_FLAT: true,
    DYNAMIC_TRAIL_MIN_R: 0.7,
    DYNAMIC_TRAIL_DISTANCE_R: 0.35,
    DYNAMIC_TRAIL_STALL_MINUTES: 45,
};

export const PORTFOLIO = {
    MAX_POSITIONS: 3,
    MARGIN_USAGE: 0.9,
    MAX_DAILY_LOSS_PCT: 0.1,
    MAX_WEEKLY_LOSS_PCT: 0.2,
};

export const TIMEFRAMES = {
    D1: "DAY",
    H4: "HOUR_4",
    H1: "HOUR",
    M15: "MINUTE_15",
    M5: "MINUTE_5",
    M1: "MINUTE",
};

export const DEV = {
    INTERVAL: 60 * 1000,
    MODE: false,
};

export const PROFILES = {
    USDCHF: {
        asia: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["asia"],
                structureMode: "greenred",
                minImpulseAtr: 0.75,
                minSwingGapAtr: 0,
                maxRetrace: 0.8,
                minAtrPercentile: 0.4,
                maxAtrPercentile: 0.9,
                minEfficiency: 0.05,
                minActivity: 0.75,
                minBodyRatio: 0.3,
                minBodyAtr: 0,
                minVolumeRatio: 0,
                maxSpreadAtr: 1,
                indicatorMode: "none",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.75,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.05,
            },
            entry: {
                type: "stop",
                bufferAtr: 0,
                expiryBars: 1,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.075,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: 0.75,
                trailDistanceR: null,
                partialAtR: 0.75,
                partialFraction: 0.5,
                trailAtr: 3,
                maxHoldMinutes: 480,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        london: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["london"],
                structureMode: "continuation",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0.05,
                maxRetrace: 1.05,
                minAtrPercentile: 0.4,
                maxAtrPercentile: 0.9,
                minEfficiency: 0.05,
                minActivity: 0,
                minBodyRatio: 0.4,
                minBodyAtr: 0.2,
                minVolumeRatio: 0,
                maxSpreadAtr: 1.25,
                indicatorMode: "score",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.75,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.25,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.05,
                expiryBars: 2,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "fixed",
                targetR: 1.5,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 0.75,
                partialFraction: 0.6,
                trailAtr: 4,
                maxHoldMinutes: 360,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        overlap: {
            signal: {
                context: "h1",
                timeframe: "M15",
                sessions: ["overlap"],
                structureMode: "greenred",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0,
                maxRetrace: 0.8,
                minAtrPercentile: 0.1,
                maxAtrPercentile: 0.75,
                minEfficiency: 0,
                minActivity: 1,
                minBodyRatio: 0,
                minBodyAtr: 0,
                minVolumeRatio: 0,
                maxSpreadAtr: 1,
                indicatorMode: "bollinger",
                minIndicatorScore: 2,
                minBollingerRoomAtr: 0.75,
                h1DirectionBars: 4,
                minH1TrendAtr: 0.1,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.01,
                expiryBars: 6,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "partial",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 1,
                partialFraction: 0.5,
                trailAtr: 4,
                maxHoldMinutes: 360,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
    },
    AUDUSD: {
        asia: {
            signal: {
                context: "h1",
                timeframe: "M15",
                sessions: ["asia"],
                structureMode: "greenred",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0.05,
                maxRetrace: 0.95,
                minAtrPercentile: 0,
                maxAtrPercentile: 0.75,
                minEfficiency: 0.15,
                minActivity: 1,
                minBodyRatio: 0.2,
                minBodyAtr: 0.3,
                minVolumeRatio: 0,
                maxSpreadAtr: 0.5,
                indicatorMode: "volume",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.5,
                h1DirectionBars: 1,
                minH1TrendAtr: 0.1,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.05,
                expiryBars: 2,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "partial",
                targetR: 1,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 1,
                partialFraction: 0.5,
                trailAtr: 4,
                maxHoldMinutes: 360,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        london: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["london"],
                structureMode: "greenred",
                minImpulseAtr: 0.75,
                minSwingGapAtr: 0,
                maxRetrace: 1.2,
                minAtrPercentile: 0.25,
                maxAtrPercentile: 0.75,
                minEfficiency: 0.15,
                minActivity: 0.75,
                minBodyRatio: 0,
                minBodyAtr: 0,
                minVolumeRatio: 0.8,
                maxSpreadAtr: 1,
                indicatorMode: "score",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 1,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.15,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.05,
                expiryBars: 5,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "fixed",
                targetR: 1.5,
                breakEvenAtR: null,
                trailActivationR: 1,
                trailDistanceR: null,
                partialAtR: 0.65,
                partialFraction: 0.5,
                trailAtr: 2,
                maxHoldMinutes: 180,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        newYork: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["newYork"],
                structureMode: "greenred",
                minImpulseAtr: 1,
                minSwingGapAtr: 0.2,
                maxRetrace: 0.95,
                minAtrPercentile: 0.6,
                maxAtrPercentile: 1,
                minEfficiency: 0.15,
                minActivity: 0,
                minBodyRatio: 0.4,
                minBodyAtr: 0.3,
                minVolumeRatio: 0,
                maxSpreadAtr: 1.25,
                indicatorMode: "score",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.5,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.05,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.02,
                expiryBars: 2,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.03,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: 1,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 0.65,
                partialFraction: 0.5,
                trailAtr: 4,
                maxHoldMinutes: 240,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
    },
    EURJPY: {
        asia: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["asia"],
                structureMode: "greenred",
                minImpulseAtr: 1,
                minSwingGapAtr: 0.2,
                maxRetrace: 0.95,
                minAtrPercentile: 0.6,
                maxAtrPercentile: 0.9,
                minEfficiency: 0.05,
                minActivity: 0,
                minBodyRatio: 0.2,
                minBodyAtr: 0.2,
                minVolumeRatio: 0,
                maxSpreadAtr: 1.25,
                indicatorMode: "none",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.5,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.25,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.01,
                expiryBars: 3,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "fixed",
                targetR: 1.5,
                breakEvenAtR: null,
                trailActivationR: 1.25,
                trailDistanceR: null,
                partialAtR: 0.65,
                partialFraction: 0.6,
                trailAtr: 2,
                maxHoldMinutes: 480,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        newYork: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["newYork"],
                structureMode: "greenred",
                minImpulseAtr: 0.75,
                minSwingGapAtr: 0.1,
                maxRetrace: 1.2,
                minAtrPercentile: 0.25,
                maxAtrPercentile: 1,
                minEfficiency: 0,
                minActivity: 1,
                minBodyRatio: 0.2,
                minBodyAtr: 0,
                minVolumeRatio: 0,
                maxSpreadAtr: 1.25,
                indicatorMode: "score",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 1,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.25,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.01,
                expiryBars: 1,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 0.65,
                partialFraction: 0.5,
                trailAtr: 4,
                maxHoldMinutes: 120,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
    },
    EURUSD: {
        asia: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["asia"],
                structureMode: "continuation",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0.1,
                maxRetrace: 1.2,
                minAtrPercentile: 0,
                maxAtrPercentile: 0.9,
                minEfficiency: 0,
                minActivity: 1,
                minBodyRatio: 0,
                minBodyAtr: 0.3,
                minVolumeRatio: 1,
                maxSpreadAtr: 1.5,
                indicatorMode: "bollinger",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.5,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.25,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.01,
                expiryBars: 2,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 0.65,
                partialFraction: 0.6,
                trailAtr: 4,
                maxHoldMinutes: 240,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        london: {
            signal: {
                context: "h1",
                timeframe: "M15",
                sessions: ["london"],
                structureMode: "greenred",
                minImpulseAtr: 0.75,
                minSwingGapAtr: 0.1,
                maxRetrace: 0.8,
                minAtrPercentile: 0.4,
                maxAtrPercentile: 0.9,
                minEfficiency: 0,
                minActivity: 0,
                minBodyRatio: 0.2,
                minBodyAtr: 0,
                minVolumeRatio: 1,
                maxSpreadAtr: 1,
                indicatorMode: "volume",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.75,
                h1DirectionBars: 2,
                minH1TrendAtr: 0.25,
            },
            entry: {
                type: "stop",
                bufferAtr: 0,
                expiryBars: 3,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 1,
                partialFraction: 0.6,
                trailAtr: 2,
                maxHoldMinutes: 480,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        overlap: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["overlap"],
                structureMode: "continuation",
                minImpulseAtr: 0.75,
                minSwingGapAtr: 0,
                maxRetrace: 1.2,
                minAtrPercentile: 0.25,
                maxAtrPercentile: 0.9,
                minEfficiency: 0.05,
                minActivity: 0.75,
                minBodyRatio: 0,
                minBodyAtr: 0,
                minVolumeRatio: 0.8,
                maxSpreadAtr: 1.25,
                indicatorMode: "score",
                minIndicatorScore: 2,
                minBollingerRoomAtr: 1,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.1,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.05,
                expiryBars: 3,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.05,
            },
            exit: {
                mode: "partial",
                targetR: 0.75,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 1,
                partialFraction: 0.6,
                trailAtr: 3,
                maxHoldMinutes: 180,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
    },
    AUDJPY: {
        asia: {
            signal: {
                context: "h1",
                timeframe: "M15",
                sessions: ["asia"],
                structureMode: "greenred",
                minImpulseAtr: 0.75,
                minSwingGapAtr: 0,
                maxRetrace: 1.2,
                minAtrPercentile: 0,
                maxAtrPercentile: 0.75,
                minEfficiency: 0.15,
                minActivity: 1,
                minBodyRatio: 0.2,
                minBodyAtr: 0.3,
                minVolumeRatio: 0,
                maxSpreadAtr: 1.25,
                indicatorMode: "none",
                minIndicatorScore: 2,
                minBollingerRoomAtr: 1,
                h1DirectionBars: 2,
                minH1TrendAtr: 0.25,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.03,
                expiryBars: 6,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.075,
            },
            exit: {
                mode: "partial",
                targetR: 1.1,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 1,
                partialFraction: 0.5,
                trailAtr: 4,
                maxHoldMinutes: 480,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        overlap: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["overlap"],
                structureMode: "greenred",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0.2,
                maxRetrace: 1.2,
                minAtrPercentile: 0.4,
                maxAtrPercentile: 0.9,
                minEfficiency: 0.15,
                minActivity: 0.75,
                minBodyRatio: 0.2,
                minBodyAtr: 0.2,
                minVolumeRatio: 0,
                maxSpreadAtr: 1,
                indicatorMode: "none",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.75,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.15,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.01,
                expiryBars: 2,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.03,
            },
            exit: {
                mode: "partial",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: 1,
                trailDistanceR: null,
                partialAtR: 1,
                partialFraction: 0.5,
                trailAtr: 3,
                maxHoldMinutes: 120,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        newYork: {
            signal: {
                context: "h1",
                timeframe: "M15",
                sessions: ["newYork"],
                structureMode: "greenred",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0.05,
                maxRetrace: 1.05,
                minAtrPercentile: 0.6,
                maxAtrPercentile: 1,
                minEfficiency: 0.05,
                minActivity: 0.75,
                minBodyRatio: 0.4,
                minBodyAtr: 0.3,
                minVolumeRatio: 0,
                maxSpreadAtr: 0.75,
                indicatorMode: "none",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 1,
                h1DirectionBars: 2,
                minH1TrendAtr: 0.4,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.05,
                expiryBars: 3,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.03,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 1,
                partialFraction: 0.6,
                trailAtr: 3,
                maxHoldMinutes: 120,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
    },
    GBPUSD: {
        london: {
            signal: {
                context: "h1",
                timeframe: "M15",
                sessions: ["london"],
                structureMode: "greenred",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0.1,
                maxRetrace: 1.05,
                minAtrPercentile: 0.1,
                maxAtrPercentile: 0.9,
                minEfficiency: 0.05,
                minActivity: 0,
                minBodyRatio: 0.4,
                minBodyAtr: 0,
                minVolumeRatio: 0.8,
                maxSpreadAtr: 0.5,
                indicatorMode: "bollinger",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 1,
                h1DirectionBars: 4,
                minH1TrendAtr: 0,
            },
            entry: {
                type: "stop",
                bufferAtr: 0,
                expiryBars: 1,
            },
            stop: {
                type: "signal",
                bufferAtr: 0,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 0.65,
                partialFraction: 0.5,
                trailAtr: 2,
                maxHoldMinutes: 480,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        overlap: {
            signal: {
                context: "h1",
                timeframe: "M15",
                sessions: ["overlap"],
                structureMode: "continuation",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0.1,
                maxRetrace: 0.95,
                minAtrPercentile: 0.4,
                maxAtrPercentile: 0.75,
                minEfficiency: 0,
                minActivity: 0,
                minBodyRatio: 0.3,
                minBodyAtr: 0,
                minVolumeRatio: 0,
                maxSpreadAtr: 1.5,
                indicatorMode: "none",
                minIndicatorScore: 2,
                minBollingerRoomAtr: 0.75,
                h1DirectionBars: 1,
                minH1TrendAtr: 0.4,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.01,
                expiryBars: 4,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.02,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 1,
                partialFraction: 0.5,
                trailAtr: 2,
                maxHoldMinutes: 180,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        newYork: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["newYork"],
                structureMode: "continuation",
                minImpulseAtr: 0.75,
                minSwingGapAtr: 0.2,
                maxRetrace: 1.05,
                minAtrPercentile: 0.1,
                maxAtrPercentile: 1,
                minEfficiency: 0,
                minActivity: 1,
                minBodyRatio: 0,
                minBodyAtr: 0,
                minVolumeRatio: 0.8,
                maxSpreadAtr: 1.25,
                indicatorMode: "none",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.75,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.25,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.05,
                expiryBars: 1,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.02,
            },
            exit: {
                mode: "partial",
                targetR: 1.1,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: 0.4,
                partialAtR: 1,
                partialFraction: 0.5,
                trailAtr: 4,
                maxHoldMinutes: 240,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
    },
    GBPCHF: {
        london: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["london"],
                structureMode: "greenred",
                minImpulseAtr: 1,
                minSwingGapAtr: 0,
                maxRetrace: 0.95,
                minAtrPercentile: 0.4,
                maxAtrPercentile: 0.9,
                minEfficiency: 0.15,
                minActivity: 1.25,
                minBodyRatio: 0,
                minBodyAtr: 0,
                minVolumeRatio: 0,
                maxSpreadAtr: 1.25,
                indicatorMode: "bollinger",
                minIndicatorScore: 2,
                minBollingerRoomAtr: 0.5,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.4,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.05,
                expiryBars: 1,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.02,
            },
            exit: {
                mode: "fixed",
                targetR: 2,
                breakEvenAtR: null,
                trailActivationR: 1,
                trailDistanceR: null,
                partialAtR: 0.65,
                partialFraction: 0.6,
                trailAtr: 2,
                maxHoldMinutes: 240,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
    },
    USDJPY: {
        overlap: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["overlap"],
                structureMode: "greenred",
                minImpulseAtr: 0.25,
                minSwingGapAtr: 0.2,
                maxRetrace: 1.05,
                minAtrPercentile: 0.1,
                maxAtrPercentile: 1,
                minEfficiency: 0.25,
                minActivity: 0.75,
                minBodyRatio: 0,
                minBodyAtr: 0,
                minVolumeRatio: 0,
                maxSpreadAtr: 1.25,
                indicatorMode: "score",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 1,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.05,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.02,
                expiryBars: 1,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.02,
            },
            exit: {
                mode: "partial",
                targetR: 1.25,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 0.75,
                partialFraction: 0.5,
                trailAtr: 2,
                maxHoldMinutes: 240,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
        newYork: {
            signal: {
                context: "m15",
                timeframe: "M15",
                sessions: ["newYork"],
                structureMode: "continuation",
                minImpulseAtr: 0.75,
                minSwingGapAtr: 0.1,
                maxRetrace: 1.05,
                minAtrPercentile: 0.4,
                maxAtrPercentile: 1,
                minEfficiency: 0,
                minActivity: 1,
                minBodyRatio: 0,
                minBodyAtr: 0.2,
                minVolumeRatio: 0,
                maxSpreadAtr: 0.5,
                indicatorMode: "bollinger",
                minIndicatorScore: 1,
                minBollingerRoomAtr: 0.75,
                h1DirectionBars: 0,
                minH1TrendAtr: 0.15,
            },
            entry: {
                type: "stop",
                bufferAtr: 0.02,
                expiryBars: 4,
            },
            stop: {
                type: "signal",
                bufferAtr: 0.02,
            },
            exit: {
                mode: "fixed",
                targetR: 1.5,
                breakEvenAtR: null,
                trailActivationR: null,
                trailDistanceR: null,
                partialAtR: 0.75,
                partialFraction: 0.5,
                trailAtr: 4,
                maxHoldMinutes: 120,
            },
            risk: {
                perTrade: 0.03,
                lastEntryMinute: 1320,
            },
        },
    },
};

export const SESSIONS = {
    asia: {
        TIME_ZONE: "Europe/London",
        END_MINUTE: 480,
        SYMBOLS: ["USDCHF", "AUDUSD", "EURJPY", "EURUSD", "AUDJPY"],
    },
    london: {
        TIME_ZONE: "America/New_York",
        END_MINUTE: 480,
        SYMBOLS: ["EURUSD", "GBPUSD", "AUDUSD", "GBPCHF", "USDCHF"],
    },
    overlap: {
        TIME_ZONE: "Europe/London",
        END_MINUTE: 1020,
        SYMBOLS: ["USDJPY", "GBPUSD", "AUDJPY", "EURUSD", "USDCHF"],
    },
    newYork: {
        TIME_ZONE: "America/New_York",
        END_MINUTE: 1020,
        SYMBOLS: ["USDJPY", "GBPUSD", "AUDUSD", "AUDJPY", "EURJPY"],
    },
};
